### ISSUE TITLE
[bug] guid download url UnityPlayer_Win64_player_il2cpp_x64

### ISSUE THREAD

**Issue by adeliktas** [SamuelTulach/ida-unity-pdb-downloader#1]
[unity-pdb] PDB name: UnityPlayer_Win64_player_il2cpp_x64
[unity-pdb] PDB guid: 7F069D49145484D805D76CFBB9E421C
[unity-pdb] PDB age: 1
[unity-pdb] Downloading from URL http://symbolserver.unity3d.com/UnityPlayer_Win64_player_il2cpp_x64.pdb/7F069D49145484D805D76CFBB9E421C1/UnityPlayer_Win64_player_il2cpp_x64.pd_...

guid is supposed to be "7F069D490145484D805D76CFBB9E421C" https://symbolserver.unity3d.com/UnityPlayer_Win64_player_il2cpp_x64.pdb/7F069D490145484D805D76CFBB9E421C1/
not sure what's exactly the issue, but considering all of the other dir have a length of 33 (https://symbolserver.unity3d.com/UnityPlayer_Win64_player_il2cpp_x64.pdb/), padding  "0" after 8 chars = 7F069D49 (followed by 24 chars 145484D805D76CFBB9E421C) seemed appropriate at least in this case.

Other than that works like a charm.

**Comment by adeliktas** [comment]
i took another look at the issue and sym dir and padding makes no sense. Something is wrong with resolving the guid...

**Comment by SamuelTulach** [comment]
https://github.com/SamuelTulach/ida-unity-pdb-downloader/blob/main/UnityPdb/UnityPdb/utils.cpp#L18

should be %08X%04X%04X%02X%02X%02X%02X%02X%02X%02X%02X to make it padded properly

will push the changes when I time

**Comment by adeliktas** [comment]
> https://github.com/SamuelTulach/ida-unity-pdb-downloader/blob/main/UnityPdb/UnityPdb/utils.cpp#L18
> 
> should be %08X%04X%04X%02X%02X%02X%02X%02X%02X%02X%02X to make it padded properly
> 
> will push the changes when I time

That solves it. I did change the PR to just include that format fix https://github.com/SamuelTulach/ida-unity-pdb-downloader/pull/2

**Comment by SamuelTulach** [comment]
Merged.
